version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    target-branch: master
    reviewers:
      - NotMyFault
    labels:
      - dependencies
    commit-message:
      prefix: "build: "
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "build: "
